/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class student_player_PentaRust */

#ifndef _Included_student_player_PentaRust
#define _Included_student_player_PentaRust
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     student_player_PentaRust
 * Method:    chooseMove
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_student_1player_PentaRust_chooseMove
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
